stages:
  - deploy_prod

deploy_prod:
  stage: deploy_prod
  script:
    - whoami
    - npm i
    - npm run dev
    - rsync -r * /var/www/nudge/parli/parli.nudge.tech --delete
    - cp /var/www/nudge/parli/.env /var/www/nudge/parli/parli.nudge.tech
    - cd /var/www/nudge/parli/parli.nudge.tech
    - rm -Rf /var/www/nudge/parli/parli.nudge.tech/storage
    - ln -sf /var/www/nudge/parli/storage /var/www/nudge/parli/parli.nudge.tech

  tags:
    - parli
  environment:
    name: production
    url: https://parli.nudge.tech
  only:
    - master
